/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project101;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author timomichaelis
 */
public class File_Creation extends javax.swing.JFrame {

    private String title ; 
    private String stardate; 
    private String endDate; 
    
    /**
     * Creates new form Folder
     */
    public File_Creation() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jStartDateText = new javax.swing.JTextField();
        jCompletionDateText = new javax.swing.JTextField();
        jTitleText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCreate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jStartDateText.setText("DD/MM/YYYY");
        jStartDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartDateTextActionPerformed(evt);
            }
        });

        jCompletionDateText.setText("DD/MM/YYYY");
        jCompletionDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCompletionDateTextActionPerformed(evt);
            }
        });

        jTitleText.setText("Psych_101");
        jTitleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTitleTextActionPerformed(evt);
            }
        });

        jLabel1.setText("Title");

        jLabel2.setText("Start Date:");

        jLabel3.setText("Completion Date");

        jCreate.setText("Create");
        jCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateActionPerformed(evt);
            }
        });

        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTitleText)
                            .addComponent(jCompletionDateText)
                            .addComponent(jStartDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStartDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCompletionDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            this.dispose();
            Flashcards_topic e = new Flashcards_topic(); 
            e.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(File_Creation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateActionPerformed
        // TODO add your handling code here:
        
        title = jTitleText.getText(); 
        stardate = jStartDateText.getText(); 
        endDate = jCompletionDateText.getText();
        System.out.println(stardate +" --> "+ endDate); 
        
        try{
            Read_write ll = new Read_write("/Users/timomichaelis/Desktop/NewFolder.1/Files/Folder/flash_titles.txt", true);
            ll.writeLine(title);
      
            String [] arrayline = ll.OpenFile(); 
            for(int i = 0; i < arrayline.length; i++){
                System.out.println(arrayline[i]);
            }
            
        }catch(IOException t){
        
        System.out.println(t.getMessage());
        }
        
            File nf = new File("/Users/timomichaelis/Desktop/NewFolder.1/Files/Folder/" + title);
            boolean can = nf.exists(); 
            System.out.println("The Directory of file is: " + nf.mkdirs());
                try{
                Read_write tt = new Read_write("/Users/timomichaelis/Desktop/NewFolder.1/Files/Folder/"+ title + "/dates.txt", true);
                Read_write ff = new Read_write("/Users/timomichaelis/Desktop/NewFolder.1/Files/Folder/"+ title + "/FlashCards.txt", true);
                Read_write gg = new Read_write("/Users/timomichaelis/Desktop/NewFolder.1/Files/Folder/"+ title + "/Score_Dates.txt", true);
                tt.writeLine(stardate);
                tt.writeLine(endDate);
                gg.writeLine("");
                TimeHandler dj = new TimeHandler(stardate,endDate); 
            
                try{
                
                    if (dj.difference() >= 35){
                        dj.assortment();
                        tt.writeLine(dj.study1);
                        tt.writeLine(dj.study2);
                        tt.writeLine(dj.study3);
                        tt.writeLine(dj.study4);
                        tt.writeLine(dj.study5);
                        
                       // tt.writeLine(dj.study1 +"," + dj.study2+","+dj.study3+
                       //         ","+dj.study4+","+dj.study5);
                    }
                    else if(dj.difference() >= 28){
                        dj.assortment();
                        tt.writeLine(dj.study1);
                        tt.writeLine(dj.study2);
                        tt.writeLine(dj.study3);
                        tt.writeLine(dj.study4);
                        
       
                      //  tt.writeLine(dj.study1 +"," + dj.study2+","+dj.study3+
                       //         ","+dj.study4);
                    }   
                    else if(dj.difference() >= 14){
                
                        dj.assortment();
                        tt.writeLine(dj.study1);
                        tt.writeLine(dj.study2);
                        tt.writeLine(dj.study3);
              
     
                      //  tt.writeLine(dj.study1 +"," + dj.study2+","+dj.study3);
                
                    }
                    else{
                    dj.assortment();
                    tt.writeLine(dj.study1);
                        tt.writeLine(dj.study2);
                        tt.writeLine(dj.study3);

     
                       // tt.writeLine(dj.study1 +"," + dj.study2);
                    
                    }
                    
            if(can == true){
                    JOptionPane.showMessageDialog(rootPane, "This file already exists!");
                }
                else{
                    
                    this.dispose();
                    Folder_Overview vF = new Folder_Overview(title); 
                    vF.setVisible(true);
                
                }
            
                }catch(ParseException ex){
                
                    System.out.print(ex.getMessage());
                }
            }catch(IOException y){
        
            System.out.println(y.getMessage());
            
            } 
            /*String [] arrayline2 = tt.OpenFile();
            for(int i = 0; i < arrayline2.length; i++){
            System.out.println(arrayline2[i]);
            }*/
        
                    
                
        
      
        
        
    }//GEN-LAST:event_jCreateActionPerformed

    private void jTitleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTitleTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTitleTextActionPerformed

    private void jStartDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jStartDateTextActionPerformed

    private void jCompletionDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCompletionDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCompletionDateTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(File_Creation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(File_Creation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(File_Creation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(File_Creation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new File_Creation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCompletionDateText;
    private javax.swing.JButton jCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jStartDateText;
    private javax.swing.JTextField jTitleText;
    // End of variables declaration//GEN-END:variables

    
}
